---

# Main tasks file for airflow role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::airflow'
    - 'role::airflow::init'
    - 'role::airflow::install'


# Installation tasks management
- name: 'INSTALL | Include installation tasks'
  import_tasks: "{{ role_path }}/tasks/manage_installation.yml"
  environment:
    AIRFLOW_HOME: '{{ airflow_config.core.airflow_home }}'
  become: True
  tags:
    - 'role::airflow'
    - 'role::airflow::install'


# Configuration tasks management
- name: 'CONFIG | Include configuration tasks'
  import_tasks: "{{ role_path }}/tasks/manage_configuration.yml"
  environment:
    AIRFLOW_HOME: '{{ airflow_config.core.airflow_home }}'
  become: True
  tags:
    - 'role::airflow'
    - 'role::airflow::config'


# Services tasks management
- name: 'SERVICE | Include services configuration tasks'
  import_tasks: "{{ role_path }}/tasks/manage_services.yml"
  become: True
  tags:
    - 'role::airflow'
    - 'role::airflow::config'
    - 'role::airflow::install'


# Connections tasks management
- name: 'CONFIG | Include connections tasks'
  import_tasks: "{{ role_path }}/tasks/manage_connections.yml"
  environment:
    AIRFLOW_HOME: '{{ airflow_config.core.airflow_home }}'
  become: True
  tags:
    - 'role::airflow'
    - 'role::airflow::config'


# Airflow variables tasks management
- name: 'CONFIG | Include connections tasks'
  import_tasks: "{{ role_path }}/tasks/manage_airflow_variables.yml"
  environment:
    AIRFLOW_HOME: '{{ airflow_config.core.airflow_home }}'
  become: True
  tags:
    - 'role::airflow'
    - 'role::airflow::config'
