---

# For Listed DAG Git Repos, clone designated branch or release to DAGS folder
- name: 'CONFIG | DAGS | Clone listed DAG git repositories'
  become_user: "{{ airflow_user_name }}"
  become: true
  git:
    repo: "{{ item.repo }}"
    dest: "{{ airflow_config.core.dags_repos_folder }}/{{ item.dest_folder }}"
    clone: true
    force: true
    version: "{{ item.branch_or_release }}"
    recursive: false
  with_items:
    - "{{ dags_git_repositories }}"

# FOR Listed DAG Git Repos, link them from download destination to configured DAGS folder
- name: 'CONFIG | DAGS | Link dag repository to dags folder'
  become_user: "{{ airflow_user_name }}"
  become: true
  file:
    state: link
    path: "{{ airflow_config.core.dags_folder }}/{{ item.dest_folder }}"
    src: "{{ airflow_config.core.dags_repos_folder }}/{{ item.dest_folder }}{% if item.dags_folder_name is defined %}/{{ item.dags_folder_name }}{% endif %}"
  with_items:
    - "{{ dags_git_repositories }}"

# For DAG-Related Git Repos, clone designated branch or release to $HOME
- name: 'CONFIG | DAGS | Clone listed DAG-related git repositories'
  become_user: "{{ airflow_user_name }}"
  become: true
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest_folder }}"
    clone: true
    force: true
    version: "{{ item.branch_or_release }}"
  with_items:
    - "{{ dags_related_git_repositories }}"


# Convert Pipfile to Requirements File
- name: 'CONFIG | DAGS | Convert Pipfile to requirements.txt'
  become_user: "{{ airflow_user_name }}"
  become: true
  args:
    chdir: "{{ airflow_config.core.dags_folder }}/{{ item.dest_folder }}"
  shell: >
    {{ airflow_virtualenv }}/bin/pipenv lock -r > requirements.txt
  with_items: "{{ dags_git_repositories }}"
  ignore_errors: true
  environment:
    LC_ALL: "en_US.utf-8"
    LANG: "en_US.utf-8"
  when: (item.pipfile | bool)


# Install DAG Pip packages from requirements.txt
- name: 'CONFIG | DAGS | Install Pip Packages from requirements.txt'
  become_user: "{{ airflow_user_name }}"
  become: true
  pip:
    requirements: "{{ airflow_config.core.dags_folder }}/{{ item.dest_folder }}/requirements.txt"
    virtualenv: "{{ airflow_virtualenv }}"
    virtualenv_python: "{{ airflow_python_version }}"
  with_items: "{{ dags_git_repositories }}"
  when: (item.pip_requirements | bool) or (item.pipfile | bool)


# Manage DAGs system dependencies
- name: 'INSTALL | Manage DAG system dependencies'
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ airflow_dag_system_dependencies }}"
