---

# Manage variables using Airflow CLI

- name: 'CONFIG | VARIABLES | Get existing variables'
  become_user: "{{ airflow_user_name }}"
  become: true
  shell: >
    set -o pipefail && \
      {{ airflow_virtualenv }}/bin/airflow variables -e /tmp/variables.json
  changed_when: false
  register: airflow_existing_variables
  no_log: True
  args:
    executable: /bin/bash
  tags:
    - airflow-test

- name: 'CONFIG | VARIABLES | Display the JSON file content'
  shell:
    cat /tmp/variables.json
  register: airflow_existing_variables
  tags:
    - airflow-test

- name: 'CONFIG | VARIABLES | Save the Json data as a Fact'
  set_fact:
    airflow_existing_variables: "{{ airflow_existing_variables.stdout | from_json }}"
  tags:
    - airflow-test

- name: 'CONFIG | VARIABLES | Merge variables'
  set_fact:
     merged_variables: "{{ airflow_existing_variables | combine(airflow_variables | items2dict) }}"
  tags:
    - airflow-test

- name: 'CONFIG | VARIABLES | Add variables'
  command: >
    {{ airflow_virtualenv }}/bin/airflow variables --set {{ item.key }} "{{ item.value }}"
  no_log: True
  with_dict: "{{ merged_variables }}"
  tags:
    - airflow-test
