---

# Role tests

- name: 'Converge | Prerequisites tasks'
  hosts: 'all'
  gather_facts: False
  tasks:
    - name: 'PREREQUISITES | APT | Do an apt-get update'
      become: True
      raw: 'apt-get update -qq'
      changed_when: False
    - name: 'PREREQUISITES | APT | Install python 2.7, sqlite3, iproute and net-tools'
      become: True
      raw: "apt-get install -qq python2.7 sqlite3 iproute{{ (ansible_host == 'airflow-docker-bionic') | ternary('2', '') }} net-tools"
      changed_when: False


- name: 'Converge | Main tasks'
  hosts: 'all'
  pre_tasks:
    - block:
        - name: 'PREREQUISITES | APT | Install locales and git'
          apt:
            name: "{{ item }}"
          changed_when: False
          with_items:
            - 'git'
            - 'locales'
        - name: 'PREREQUISITES | Prepare locales management - Ubuntu'
          copy:
            dest: '/etc/locale.conf'
            content: 'LANG=en_US.UTF-8'
          changed_when: False
        - name: 'PREREQUISITES | Prepare locales management - Debian'
          copy:
            dest: '/etc/locale.gen'
            content: "en_US.UTF-8 UTF-8\n"
          changed_when: False
        - name: 'PREREQUISITES | Update locales'
          command: 'locale-gen'
          changed_when: False
          when: "(ansible_distribution_release | lower) != 'trusty'"
        - name: 'PREREQUISITES | Update locales'
          command: 'locale-gen en_US.UTF-8'
          changed_when: False
          when: "(ansible_distribution_release | lower) == 'trusty'"
      become: True
  roles:
    - role: "ansible-role-airflow"
  environment:
    LC_ALL: 'en_US.UTF-8'
